CoffeeShop/CoffeeShop/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CoffeeShop.Models
{
    public class ItemsController : Controller
    {
        //TODO: Try to incorporate a try-catch as last challenge to have a more user friendly way of dealing with errors for protection
        private ItemDAO dao = new ItemDAO();


        // GET: Items
        public ActionResult Index()
        {
            return View(dao.GetItemList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = dao.GetItem((int)id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemId,Name,Description,Quantity,Price")] Item item)
        {
            if (ModelState.IsValid)
            {
                dao.AddItem(item);
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = dao.GetItem((int)id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemId,Name,Description,Quantity,Price")] Item item)
        {
            if (ModelState.IsValid)
            {
                dao.EditItem(item);
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = dao.GetItem((int)id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            dao.DeleteItem(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                dao.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CoffeeShop/CoffeeShop/Controllers/MenuController.cs
using CoffeeShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoffeeShop.Controllers
{
    public class MenuController : Controller
    {
        private ItemDAO dao = new ItemDAO();

        // GET: Menu
        public ActionResult Index()
        {
            //if (Session["Cart"] == null)
            //{
            //    List<Item> item = new List<Item>();
            //    Item x = null;
            //    item.Add(x);
            //    Session["Cart"] = item;
            //    return View(dao.GetItemList(), (List<Item>)Session["Cart"]);
            //}
            return View(dao.GetItemList());
        }

        public ActionResult ItemSort(string column)
        {
            return View("Index", dao.ItemSort(column));
        }

        public ActionResult Add(int id = 0)/*, int quantity = 0)*/
        {
            //dao.UpdateQuantity(id, quantity);
            CoffeeEntities db = new CoffeeEntities();
            
            if (id == 0 && Session["Cart"] != null)
            {
                //List<Item> cart = (List<Item>)(Session["Cart"]);
                //Item item = ()
                return View("Add", Session["Cart"]);
            }
            else if (id == 0)
            {
                //List<Item> cart = (List<Item>)(Session["Cart"]);
                //Item item = ()
                return View("Add", Session["Cart"] = null);
            }
            else
            {
                //Check if the Cart already exists
                if (Session["Cart"] == null)
                {
                    //if it doesn't make a new list of books

                    List<Item> cart = new List<Item>();
                    //add this book to it
                    cart.Add((from i in db.Items
                              where i.ItemId == id
                              select i).Single());

                    //add the list to the session
                    Session.Add("Cart", cart);
                }
                else
                {
                    //if it does exist need to get the list
                    List<Item> cart = (List<Item>)(Session["Cart"]);
                    //add this book to the list
                    cart.Add((from b in db.Items
                              where b.ItemId == id
                              select b).Single());
                    //add the list to the session
                    //Session["Cart"] = cart;
                }

                return View(); 
            }
        }

        public ActionResult Clear()
        {
            Session.Clear();
            //for (int i = 0; i < dao.GetListLength(); i++)
            //{
            //    dao.UpdateQuantity(i, 0);
            //}
            return View();
        }
    }
}

CoffeeShop/CoffeeShop/Controllers/UserRegController.cs
using CoffeeShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoffeeShop.Controllers
{
    public class UserRegController : Controller
    {
        // GET: UserReg
        public ActionResult Index()
        {
            CoffeeEntities ORM = new CoffeeEntities();
            ViewBag.Users = ORM.Users.ToList();

            return View();

        }

        public ActionResult UserReg(User data)/*string firstName ="", string lastName = "", string email = "", double phoneNumber = 0, string password = "", string securityQuestion = "", string securityAnswer = "")*/
        {
            //do data.blank and still add to viewbag to use for registration feedback. but add to the database

            //ViewBag.FirstName = firstName;
            //ViewBag.LastName = lastName;
            //ViewBag.Email = email;
            //ViewBag.PhoneNumber = phoneNumber;
            //ViewBag.Password = password;
            //ViewBag.SecurityQuestion = securityQuestion;
            //ViewBag.SecurityAnswer = securityAnswer;

            CoffeeEntities ORM = new CoffeeEntities();
            ViewBag.Users = ORM.Users.ToList();



            if (ModelState.IsValid)
            {
                try
                {
                    ORM.Users.Add(data);
                    ORM.SaveChangesAsync();
                    ViewBag.message = $"Account with has been added";
                }
                catch (Exception e)
                {
                    ViewBag.message = $"Error {e.Message}";//$"{data.Email} is not in the database and is not a valid customer.";
                }
            }
            else
            {
                ViewBag.message = "User is not valid, could not add to DataBase.";
            }

            return View();
        }
    }
}

CoffeeShop/CoffeeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Menu", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("User Registration", "Index", "UserReg")</li>
                    <li>@Html.ActionLink("Item Spot", "Index", "Items")</li>
                    <li>@Html.ActionLink("Menu", "Index", "Menu")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; CoffeeShop - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

@*<style>
    fieldset{
        text-align: center;
    }
    input[type="text"] {
        display: block;
        margin: 0 auto;
    }
    #Email {
        display: block;
        margin: 0 auto;
    }
    #EmailWarning {
        display: block;
        margin: 0 auto;
    }
    #PhoneNumber {
        display: block;
        margin: 0 auto;
    }
    #PhoneWarning {
        display: block;
        margin: 0 auto;
    }
    #Password {
        display: block;
        margin: 0 auto;
    }
    #Password2 {
        display: block;
        margin: 0 auto;
    }
    #PasswordWarning {
        display: block;
        margin: 0 auto;
    }
    #security {
        display: block;
        margin: 0 auto;
    }
    #submit {
        display: block;
        margin: 0 auto;
    }
    #title {
        text-align:center;
    }
</style>*@